apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: v1-client
spec:
  selector:
    matchLabels:
      app: v1-client
  serviceName: v1-client
  replicas: 1
  template:
    metadata:
      labels:
        app: v1-client
        v1-purpose: client
    spec:
      containers:
        - name: pocket
          image: poktnetwork/pocket-v1:main-dev
          command: ["/bin/bash", "-c", "--"]
          args: ["while true; do sleep 30; done;"]
          ports:
            - containerPort: 8221
              name: pre2p
            - containerPort: 8222
              name: p2p
          volumeMounts:
            - name: genesis-volume
              # This path is hardcoded in the code, so it must match.
              # https://github.com/pokt-network/pocket/blob/9e3374f511c8cd66beb33a5264b60b10a49d185e/app/client/main.go#L49
              mountPath: /go/src/github.com/pokt-network/pocket/build/config/genesis.json
              subPath: genesis.json
      volumes:
        - name: config-volume
          configMap:
            name: v1-validator2-configs
        - name: genesis-volume
          configMap:
            name: v1-localnet-genesis
---

