apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: v1-validator3
spec:
  selector:
    matchLabels:
      app: v1-validator3
  serviceName: v1-validator3
  replicas: 1
  template:
    metadata:
      labels:
        app: v1-validator3
        v1-purpose: validator
    spec:
      containers:
        - name: pocket
          image: poktnetwork/pocket-v1:main-dev
          args:
            - pocket
            - -config=/configs/config.json
          ports:
            - containerPort: 8221
              name: pre2p
            - containerPort: 8222
              name: p2p
          volumeMounts:
            - name: config-volume
              mountPath: /configs
            - name: genesis-volume
              mountPath: /genesis.json
              subPath: genesis.json
            - name: v1-validator3-blockstore
              mountPath: /blockstore
      volumes:
        - name: config-volume
          configMap:
            name: v1-validator3-configs
        - name: genesis-volume
          configMap:
            name: v1-localnet-genesis
  volumeClaimTemplates:
    - metadata:
        name: v1-validator3-blockstore
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: v1-validator3
  labels:
    app: v1-validator3
spec:
  ports:
    - port: 8221
      name: pre2p
    - port: 8222
      name: p2p
  # clusterIP: None
  selector:
    app: v1-validator3
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: v1-validator3-configs
data:
  config.json: |
    {
      "root_dir": "/data",
      "genesis_source": {
        "file": {
          "path": "/genesis.json"
        }
      },
      "private_key": "2b000000000000000000000000000000000000000000000000000000000000001ba66c6751506850ae0787244c69476b6d45fb857a914a5a0445a24253f7b810",
      "enable_telemetry": true,
      "p2p": {
        "consensus_port": 8221,
        "use_raintree": true,
        "connection_type": "tcp",
        "protocol": "tcp",
        "address": "0.0.0.0:8222",
        "peers": [
          "v1-validator1:8222",
          "v1-validator3:8222",
          "v1-validator3:8222",
          "v1-validator4:8222"
        ]
      },
      "consensus": {
        "max_mempool_bytes": 500000000,
        "max_block_bytes": 4000000,
        "pacemaker": {
          "timeout_msec": 5000,
          "manual": true,
          "debug_time_between_steps_msec": 1000
        }
      },
      "pre_persistence": {
        "capacity": 99999,
        "mempool_max_bytes": 99999,
        "mempool_max_txs": 99999
      },
      "persistence": {
        "postgres_url": "postgres://postgres:postgres@postgresql:5432/postgres",
        "schema": "validator3",
        "block_store_path": "/blockstore"
      },
      "utility": {},
      "telemetry": {
        "address": "0.0.0.0:9000",
        "endpoint": "/metrics"
      }
    }
