apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: v1-validator2
spec:
  selector:
    matchLabels:
      app: v1-validator2
  serviceName: v1-validator2
  replicas: 1
  template:
    metadata:
      labels:
        app: v1-validator2
        v1-purpose: validator
    spec:
      containers:
        - name: pocket
          image: poktnetwork/pocket-v1:pr-124-dev
          args:
            - pocket
            - -config=/configs/config.json
          ports:
            - containerPort: 8221
              name: pre2p
            - containerPort: 8222
              name: p2p
          volumeMounts:
            - name: config-volume
              mountPath: /configs
            - name: genesis-volume
              mountPath: /genesis.json
              subPath: genesis.json
      volumes:
        - name: config-volume
          configMap:
            name: v1-validator2-configs
        - name: genesis-volume
          configMap:
            name: v1-localnet-genesis
---
apiVersion: v1
kind: Service
metadata:
  name: v1-validator2
  labels:
    app: v1-validator2
spec:
  ports:
    - port: 8221
      name: pre2p
    - port: 8222
      name: p2p
  # clusterIP: None
  selector:
    app: v1-validator2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: v1-validator2-configs
data:
  config.json: |
    {
      "root_dir": "/data",
      "genesis_source": {
        "file": {
          "path": "/genesis.json"
        }
      },
      "private_key": "2d00000000000000000000000000000000000000000000000000000000000000ee37d8c8e9cf42a34cfa75ff1141e2bc0ff2f37483f064dce47cb4d5e69db1d4",
      "pre2p": {
        "consensus_port": 8221,
        "use_raintree": true,
        "connection_type": "tcp"
      },
      "p2p": {
        "protocol": "tcp",
        "address": "0.0.0.0:8222",
        "peers": [
          "v1-validator1:8222",
          "v1-validator2:8222",
          "v1-validator3:8222",
          "v1-validator4:8222"
        ]
      },
      "consensus": {
        "max_mempool_bytes": 500000000,
        "max_block_bytes": 4000000,
        "pacemaker": {
          "timeout_msec": 5000,
          "manual": true,
          "debug_time_between_steps_msec": 1000
        }
      },
      "pre_persistence": {
        "capacity": 99999,
        "mempool_max_bytes": 99999,
        "mempool_max_txs": 99999
      },
      "persistence": {
        "postgres_url": "postgres://postgres:postgres@postgresql:5432/postgres",
        "schema": "validator2"
      },
      "utility": {}
    }
